<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapbind="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://datex2.eu/wsdl/supplierPush/2_0" xmlns:d2ns="http://datex2.eu/schema/2/2_0" name="supplierPush" targetNamespace="http://datex2.eu/wsdl/supplierPush/2_0">
	<documentation>
		Version 2.2 - 31 May 2012
		This document describes the DATEX II Push Service with WSDL 1.1
		This wsdl document is the reference with which each DATEX II Push Web Service has to be built
		Refer http://datex2.eu
	</documentation>
	<types>
		<xs:schema targetNamespace="http://datex2.eu/wsdl/supplierPush/2_0">
			<xs:import namespace="http://datex2.eu/schema/2/2_0" schemaLocation="DATEXIISchema_2_2_2_Parking_1_0_a.xsd"/>
			<!-- Here, the "namespace" MUST be the same as the used DATEXII schema targetNamespace -->
			<!-- Here, the "schemaLocation" depends on each implementation and MUST be filled  by each developer, for instance  "ffile:///C:/DATEX2/DATEXIISchema_2_2_1.xsd"-->
		</xs:schema>
	</types>
	<message name="supplierMessage">
		<part name="body" element="d2ns:d2LogicalModel"/>
	</message>
	<message name="outputMessage">
		<part name="body" element="d2ns:d2LogicalModel"/>
	</message>
	<portType name="supplierPushInterface">
		<operation name="putDatex2Data">
			<input message="tns:supplierMessage"/>
			<output message="tns:outputMessage"/>
		</operation>
	</portType>
	<binding name="supplierPushSoapBinding" type="tns:supplierPushInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="putDatex2Data">
			<soap:operation soapAction="http://datex2.eu/wsdl/supplierPush/2_0/putDatex2Data" style="document"/>
			<input>
				<soapbind:body parts="body" use="literal"/>
			</input>
			<output>
				<soapbind:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="supplierPushService">
		<port name="supplierPushSoapEndPoint" binding="tns:supplierPushSoapBinding">
			<soap:address location="http://localhost:8080/supplierPushService/2_0"/>
			<!-- Here, the "location" depends on each implementation and MUST be filled  by each developer, for instance "http://localhost:8080/supplierPushService/2_0"-->
		</port>
	</service>
</definitions>
